name: Docs Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repository:
        description: >
          [Optional] Repository name with owner. For example, newron/newron-client.
           Defaults to the repository that triggered a workflow.
        required: false
        default: ""
      ref:
        description: >
          [Optional] The branch, tag or SHA to checkout. When checking out the repository that
           triggered a workflow, this defaults to the reference or SHA for that event. Otherwise,
           uses the default branch.
        required: false
        default: ""

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mkgendocs
        run: pip install mkgendocs
      - name: Set-URL Origin
        run: git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.ORGANISATION }}/${{ secrets.REPOSITORY }}.git
      - name: Generate Docs
        run: gendocs --config mkgendocs.yml
      - name: Copy
        uses: ./.github/actions/copycat
        with:
          personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          src_path: /docs/sources/api
          dst_path: /docs/pages/
          src_branch: main
          dst_branch: main
          dst_owner: ${{ secrets.ORGANISATION }}
          dst_repo_name: ${{ secrets.REPOSITORY }}
